[package]
name = "axolotl-rs"
version = "0.1.0"
authors = ["loading..."]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
